### ISSUE TITLE
Create a standard pipeline params file including all options for (sub-)modules

### ISSUE THREAD

**Issue by abhi18av** [mtb-bioinformatics/mtbseq-nf#23]
Then, let's try to use the following pattern

```nextflow
TBBWA {
// global params

// module params

// <- Here we add the module level params mentioned in tbbwa.nf file, which a user can override through a central location ->
resultsDir = "${params.outdir}/tbbwa"
saveMode = 'copy'
shouldPublish = true
}


```

I think that we're at a stage we can try some stuff out, I'd be curious to see how the `params.outdir` behaves within this context.

_Originally posted by @abhi18av in https://github.com/emilyncosta/mtbseq-nf/issues/19#issuecomment-885039728_

**Comment by Mxrcon** [comment]
ok, lets give a try to it

**Comment by abhi18av** [comment]
@Mxrcon ,

I'm creating these tasks as part of project planning. Anyone of us could pick either task based on the time available 😉 

It's important to self-assign a task whenever we pick a task so that the team member is aware.

**Comment by Mxrcon** [comment]
ok! I'll assign myself if i start this task!
