### ISSUE TITLE
Extract all native tool commands from the logs

### ISSUE THREAD

**Issue by abhi18av** [mtb-bioinformatics/mtbseq-nf#29]
We can create an alternative Nextflow native version of this workflow using the knowledge of the underlying commands.

**Comment by Mxrcon** [comment]
@abhi18av do you have complete logs somewhere? I can give some time to this task today or tomorrow.

**Comment by abhi18av** [comment]
I've just shared the link with you via email :)

**Comment by Mxrcon** [comment]
ok! Thank you!
