### ISSUE TITLE
Create a DAG file for the batch/parallel workflows

### ISSUE THREAD

**Issue by abhi18av** [mtb-bioinformatics/mtbseq-nf#32]
@Mxrcon, I'd really appreciate if you could take care of this issue after #25

**Comment by Mxrcon** [comment]
yes sure!

**Comment by abhi18av** [comment]
@Mxrcon , could you please raise a PR (against `dev` branch)  for the DAG file as part of #32 

There would be two DAG files, 
1. Batch analysis
2. Parallel analysis

These need to be added into the resources folder and the readme file.

**Comment by Mxrcon** [comment]
Ok, I'll add them asap
