### ISSUE TITLE
[BUG] conda package name

### ISSUE THREAD

**Issue by Mxrcon** [mtb-bioinformatics/mtbseq-nf#51]
hey there :wave:, during my tests using conda i found a small typo on `conf/conda`

the conda package is named like this `bioconda::mtbseq:1.0.3`
and nextflow will throw this error: 
```
    UnavailableInvalidChannel: The channel is not accessible or is invalid.
      channel name: bioconda:
      channel url: https://conda.anaconda.org/bioconda:
      error code: 404
``` 
This could be fixed writing the conda package name like this: `bioconda:mtbseq:1.0.3` or this `bioconda::mtbseq=1.0.3`

I'll take some time to implement this change asap on the master branch as it seems to be urgent!

**Comment by abhi18av** [comment]
@Mxrcon , first time I see `bug` and `enhancement` used together 😅 

This is definitely a `bug`.
