### ISSUE TITLE
Add QC_REPORTS workflow

### ISSUE THREAD

**Issue by abhi18av** [mtb-bioinformatics/mtbseq-nf#55]
With recent experience on some projects, we lost quite some time on  the analysis when the base genomes weren't even making it through the base QC checks such as size etc.

I think it's worth it to add an optional QC_REPORTS workflow, which takes the initial genomes (before renaming) and then prepares FASTQC and MULTIQC report for the genomes.

The user should be able to 
- Run _only_ `QC_REPORTS` workflow
- Run `QC_REPORTS` along with the current setup (default)

**Comment by abhi18av** [comment]
Hi @Mxrcon , would it be possible for you to take a look into this task?

**Comment by Mxrcon** [comment]
@abhi18av yes sure, sorry for late answe. I'll give it attention.

**Comment by abhi18av** [comment]
No problem at all Dávi, hope you had a great vacation! 🏖️

**Comment by Mxrcon** [comment]
It was really nice! but now it's time to came back to work :sunglasses:
