### ISSUE TITLE
Consider creating a custom container with all the necessary deps.

### ISSUE THREAD

**Issue by abhi18av** [mtb-bioinformatics/MTBseq-nf#67]
I'm thinking that now we can publish a custom docker container starting from `micromamba` image after this - containing the `fastqc` and `multiqc` deps as well 🤔 

_Originally posted by @abhi18av in https://github.com/mtb-bioinformatics/mtbseq-nf/pull/64#pullrequestreview-951010173_

NOTE: This task should only be initiated if the custom multi-container (mulled) request doesn't work out. Refer here https://github.com/mtb-bioinformatics/mtbseq-nf/issues/60

**Comment by Mxrcon** [comment]
@abhi18av, Seems like a very good option! this way we can optimize the runs when using cloud computing!
