### ISSUE TITLE
GATK/Nextflow Java environment differences

### ISSUE THREAD

**Issue by jloubser** [mtb-bioinformatics/mtbseq-nf#70]
GATK requires java 8, but Nextflow at least Java 11.
One can't launch Nextflow when you've activated the mtbseq-env. But when you run the pipeline from the base environment it runs up until BATCH_ANALYSIS:TBFULL and then gives an error at: 
Command executed:
    gatk-register GenomeAnalysisTK.jar

**Comment by abhi18av** [comment]
Hopefully, this one was resolved in our discussion yesterday?

**Comment by jloubser** [comment]
Almost, I opened up a discussion in the general tab you created. I can't start Nextflow when that environment is activated. Is there a way around that..? Mtbseq worked but the Amend and Joint and another one is empty. I suspect this is Mtbseq-specific and not this pipeline.

**Comment by abhi18av** [comment]
Ah no - this is related to #72 

@jloubser , if you want to run via the nextflow layer, then please deactivate the `mtbseq-nf-env` since the `-profile conda` will instruct nextflow to automatically pick that env for executing mtbseq.

But for executing NF itself, please use the env with `Java-11`

**Comment by jloubser** [comment]
Ah! I get it! I ''think'' I tried it before and there were errors. But I'll give it a try! Thank you!
