### ISSUE TITLE
Error related to log4j2

### ISSUE THREAD

**Issue by Mxrcon** [mtb-bioinformatics/MTBseq-nf#76]
I'm trying to run the pipeline on a PBS cluster and during the TBBWA step, I'm getting this very odd error:
```
ERROR StatusLogger Unable to create class org.apache.logging.log4j.core.impl.Log4jContextFactory specified in jar:file:/laboratorio/sabmi/karla.lima/sabmi_sra_marilia/mtbseq_nf_test/mtbseq-nf/conda_envs/mtbseq-nf-env/opt/gatk-3.8/GenomeAnalysisTK.jar!/META-INF/log4j-provider.properties
ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
INFO  16:18:38,339 GenomeAnalysisEngine - Deflater: JdkDeflater 
INFO  16:18:38,340 GenomeAnalysisEngine - Inflater: JdkInflater 
INFO  16:18:38,341 GenomeAnalysisEngine - Strictness is SILENT 
INFO  16:18:38,499 GenomeAnalysisEngine - Downsampling Settings: Method: BY_SAMPLE, Target Coverage: 10000 
INFO  16:18:38,510 SAMDataSource$SAMReaders - Initializing SAMRecords in serial 
INFO  16:18:38,587 SAMDataSource$SAMReaders - Done initializing BAM readers: total time 0.07 
##### ERROR ------------------------------------------------------------------------------------------

``` 

I'm using a new conda environtment provided by the recipe on this repository, I'm also using the correct GATK jar.

**Comment by abhi18av** [comment]
This seems related https://github.com/ngs-fzb/MTBseq_source/issues/23 and reported for a conda_env, which I haven't been able to reproduce on my setup yet.

Note that I haven't been able to reproduce either, this issue using the `docker` container

**Comment by Mxrcon** [comment]
I'm testing the GATKjar version 3.8.1 (GenomeAnalysisTK-3.8-1-0-gf15c1c3ef), avaible on this link: `https://storage.googleapis.com/gatk-software/package-archive/gatk/GenomeAnalysisTK-3.8-1-0-gf15c1c3ef.tar.bz2`

As suggested on this issue, so we can see if updating the jar solves the problem with mtbseq

**Comment by Mxrcon** [comment]
After a long test on IEC Cluster the issue seems to be fixed, If it's okay to you @abhi18av, I'll close this issue and keep it as a possible troubleshooting for future use.

**Comment by abhi18av** [comment]
Brilliant! 

@Mxrcon , would you mind adding a general outline of the solution please?

**Comment by Mxrcon** [comment]
Sure!
- [ ] Download a new GATK tar

```terminal
wget https://storage.googleapis.com/gatk-software/package-archive/gatk/GenomeAnalysisTK-3.8-1-0-gf15c1c3ef.tar.bz2
```
- [ ] Untar the GATK.jar
```terminal
 tar -xvf GenomeAnalysisTK-3.8-1-0-gf15c1c3ef.tar.bz2
```

- [ ] Register the new GATK and use on the pipeline as usual
```terminal
 gatk-register GenomeAnalysisTK-3.8-1-0-gf15c1c3ef/GenomeAnalysisTK.jar
```

**Comment by abhi18av** [comment]
Hmm, I see.

In that case, do you think it's worth upgrading the default gatk version within the pipeline?

I have updated the title of this issue to help anyone discover the cause of this issue earlier.
