### ISSUE TITLE
Single-end reads

### ISSUE THREAD

**Issue by AroobAlhumaidy** [mtb-bioinformatics/MTBseq-nf#81]
Hello, 

Dose the pipeline works on single-end reads? 

Thanks 

Best, 
Aroob

**Comment by abhi18av** [comment]
Hi @AroobAlhumaidy , 

Thanks for your interest in the wrapper!

Yes the single end reads are accommodated as a direct consequence of using `MTBseq` https://github.com/ngs-fzb/MTBseq_source/blob/master/MANUAL.md#overview
